name: IAmCatVR
options:
  bundleIdPrefix: com.pedro
settings:
  base:
    IPHONEOS_DEPLOYMENT_TARGET: 15.0
    SWIFT_VERSION: 5.0
    TARGETED_DEVICE_FAMILY: 1
    SUPPORTS_MACCATALYST: NO
targets:
  IAmCatVR:
    type: application
    platform: iOS
    deploymentTarget: "15.0"
    sources:
      - path: .
        excludes:
          - project.yml
          - Info.plist
    info:
      path: Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pedro.iamcatvr
        PRODUCT_NAME: IAmCatVR
        CODE_SIGNING_ALLOWED: NO
        CODE_SIGNING_REQUIRED: NO
        CODE_SIGN_IDENTITY: ""
        ENABLE_BITCODE: NO
