name: SuperhotVR
options:
  bundleIdPrefix: com.nexa
  deploymentTarget:
    iOS: '15.0'
targets:
  SuperhotVR:
    type: application
    platform: iOS
    sources:
      - path: Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.nexa.superhotvr
        PRODUCT_NAME: SuperhotVR
        SWIFT_VERSION: '5.0'
        TARGETED_DEVICE_FAMILY: '1'
        IPHONEOS_DEPLOYMENT_TARGET: '15.0'
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_CFBundleDisplayName: SUPERHOT VR
        INFOPLIST_KEY_NSCameraUsageDescription: Camera usada para 6DoF e hand tracking das duas maos.
        INFOPLIST_KEY_UIRequiredDeviceCapabilities: arkit
        INFOPLIST_KEY_UIRequiresFullScreen: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        ASSETCATALOG_COMPILER_APPICON_NAME: ''
        CODE_SIGN_STYLE: Automatic
        ENABLE_BITCODE: NO
    dependencies:
      - sdk: ARKit.framework
      - sdk: Vision.framework
      - sdk: SceneKit.framework
      - sdk: UIKit.framework
